parameters:
    redis_host: '%env(REDIS_HOST)%'
    redis_port: '%env(int:REDIS_PORT)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Redis\RedisClient:
        arguments:
            $host: '%redis_host%'
            $port: '%redis_port%'